version: "3.3"
services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   restart: always
  #   ports:
  #     - "3050:80"
  #   depends_on:
  #     - backend
  #     - frontend
  mysqldb:
    image: mysql:8.4
    restart: always
    volumes:
      - ./backend/mysqldata:/var/lib/mysql
    env_file:
      - ./backend/.env.development.local
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #   MYSQL_DATABASE: ${DB_NAME}
    #   MYSQL_USER: ${DB_USERNAME}
    #   MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3307:3306
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.development.local
    environment:
      - NODE_ENV=development
    depends_on:
      - mysqldb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true
